package com.zenika.aic.core.libs.sensor;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recording.proto

public final class Recording {
  private Recording() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class recordingPayload extends
      com.google.protobuf.GeneratedMessage {
    // Use recordingPayload.newBuilder() to construct.
    private recordingPayload() {
      initFields();
    }
    private recordingPayload(boolean noInit) {}
    
    private static final recordingPayload defaultInstance;
    public static recordingPayload getDefaultInstance() {
      return defaultInstance;
    }
    
    public recordingPayload getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Recording.internal_static_recordingPayload_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Recording.internal_static_recordingPayload_fieldAccessorTable;
    }
    
    // optional string recFilename = 1;
    public static final int RECFILENAME_FIELD_NUMBER = 1;
    private boolean hasRecFilename;
    private String recFilename_ = "";
    public boolean hasRecFilename() { return hasRecFilename; }
    public String getRecFilename() { return recFilename_; }
    
    // optional uint32 startStop = 2;
    public static final int STARTSTOP_FIELD_NUMBER = 2;
    private boolean hasStartStop;
    private int startStop_ = 0;
    public boolean hasStartStop() { return hasStartStop; }
    public int getStartStop() { return startStop_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRecFilename()) {
        output.writeString(1, getRecFilename());
      }
      if (hasStartStop()) {
        output.writeUInt32(2, getStartStop());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRecFilename()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRecFilename());
      }
      if (hasStartStop()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getStartStop());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static recordingPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static recordingPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static recordingPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static recordingPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static recordingPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static recordingPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static recordingPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static recordingPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static recordingPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static recordingPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(recordingPayload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private recordingPayload result;
      
      // Construct using Recording.recordingPayload.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new recordingPayload();
        return builder;
      }
      
      protected recordingPayload internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new recordingPayload();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return recordingPayload.getDescriptor();
      }
      
      public recordingPayload getDefaultInstanceForType() {
        return recordingPayload.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public recordingPayload build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private recordingPayload buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public recordingPayload buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        recordingPayload returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof recordingPayload) {
          return mergeFrom((recordingPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(recordingPayload other) {
        if (other == recordingPayload.getDefaultInstance()) return this;
        if (other.hasRecFilename()) {
          setRecFilename(other.getRecFilename());
        }
        if (other.hasStartStop()) {
          setStartStop(other.getStartStop());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRecFilename(input.readString());
              break;
            }
            case 16: {
              setStartStop(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string recFilename = 1;
      public boolean hasRecFilename() {
        return result.hasRecFilename();
      }
      public String getRecFilename() {
        return result.getRecFilename();
      }
      public Builder setRecFilename(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRecFilename = true;
        result.recFilename_ = value;
        return this;
      }
      public Builder clearRecFilename() {
        result.hasRecFilename = false;
        result.recFilename_ = getDefaultInstance().getRecFilename();
        return this;
      }
      
      // optional uint32 startStop = 2;
      public boolean hasStartStop() {
        return result.hasStartStop();
      }
      public int getStartStop() {
        return result.getStartStop();
      }
      public Builder setStartStop(int value) {
        result.hasStartStop = true;
        result.startStop_ = value;
        return this;
      }
      public Builder clearStartStop() {
        result.hasStartStop = false;
        result.startStop_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:recordingPayload)
    }
    
    static {
      defaultInstance = new recordingPayload(true);
      Recording.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:recordingPayload)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_recordingPayload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recordingPayload_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017recording.proto\":\n\020recordingPayload\022\023\n" +
      "\013recFilename\030\001 \001(\t\022\021\n\tstartStop\030\002 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_recordingPayload_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_recordingPayload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_recordingPayload_descriptor,
              new String[] { "RecFilename", "StartStop", },
              recordingPayload.class,
              recordingPayload.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
