/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.scoping;

import org.xtext.aic.dsl.scoping.AbstractAiC_DSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AiC_DSLScopeProvider extends AbstractAiC_DSLScopeProvider {
}
