/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl;

import org.xtext.aic.dsl.AbstractAiC_DSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AiC_DSLRuntimeModule extends AbstractAiC_DSLRuntimeModule {
}
