/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AiC_DSLValidator extends AbstractAiC_DSLValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					AiC_DSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
