/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getIncludes <em>Includes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getPlanes <em>Planes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getAirports <em>Airports</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getAirlines <em>Airlines</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Includes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Includes}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Includes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Includes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Includes()
   * @model containment="true"
   * @generated
   */
  EList<Includes> getIncludes();

  /**
   * Returns the value of the '<em><b>Planes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Plane}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Planes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Planes</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Planes()
   * @model containment="true"
   * @generated
   */
  EList<Plane> getPlanes();

  /**
   * Returns the value of the '<em><b>Airports</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Airport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Airports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airports</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Airports()
   * @model containment="true"
   * @generated
   */
  EList<Airport> getAirports();

  /**
   * Returns the value of the '<em><b>Airlines</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Airline}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Airlines</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airlines</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Airlines()
   * @model containment="true"
   * @generated
   */
  EList<Airline> getAirlines();

} // Model
