/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.validation;

import org.xtext.aic.dsl.validation.AbstractAiC_DSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AiC_DSLValidator extends AbstractAiC_DSLValidator {
}
