/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.aiC_DSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aic.dsl.aiC_DSL.Model#getSensors <em>Sensors</em>}</li>
 * </ul>
 *
 * @see org.xtext.aic.dsl.aiC_DSL.AiC_DSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.aic.dsl.aiC_DSL.Sensor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sensors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensors</em>' containment reference list.
   * @see org.xtext.aic.dsl.aiC_DSL.AiC_DSLPackage#getModel_Sensors()
   * @model containment="true"
   * @generated
   */
  EList<Sensor> getSensors();

} // Model
