/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class AiC_DSLUiModule extends AbstractAiC_DSLUiModule {
}
