/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AiC_DSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/aic/dsl/parser/antlr/internal/InternalAiC_DSL.tokens");
	}
}
