/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.aic.dsl.parser.antlr.internal.InternalAiC_DSLParser;
import org.xtext.aic.dsl.services.AiC_DSLGrammarAccess;

public class AiC_DSLParser extends AbstractAntlrParser {

	@Inject
	private AiC_DSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAiC_DSLParser createParser(XtextTokenStream stream) {
		return new InternalAiC_DSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AiC_DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AiC_DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
