/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AiC_DSLRuntimeModule extends AbstractAiC_DSLRuntimeModule {
}
