/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AiC_DSLStandaloneSetup extends AiC_DSLStandaloneSetupGenerated {

	def static void doSetup() {
		new AiC_DSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
