/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.ui.contentassist;

import org.xtext.aic.dsl.ui.contentassist.AbstractAiC_DSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AiC_DSLProposalProvider extends AbstractAiC_DSLProposalProvider {
}
