/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAiC_DSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.xtext.aic.dsl.aiC_DSL.AiC_DSLPackage.eINSTANCE);
		return result;
	}
	
}
