/*
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAiC_DSLScopeProvider extends DelegatingScopeProvider {
}
