/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.xtext.example.mydsl.idea.lang.psi.impl.MyDslFileImpl;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<MyDslFileImpl>>(MyDslLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final MyDslGrammarAccess GRAMMAR_ACCESS = MyDslLanguage.INSTANCE.getInstance(MyDslGrammarAccess.class);

	private static class ModelFactory {
		public static IGrammarAwareElementType createModelElementType() {
			return new IGrammarAwareElementType("Model_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelRule());
		}
		public static IGrammarAwareElementType createModel_GroupElementType() {
			return new IGrammarAwareElementType("Model_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getGroup());
		}
		public static IGrammarAwareElementType createModel_IncludesAssignment_0ElementType() {
			return new IGrammarAwareElementType("Model_IncludesAssignment_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getIncludesAssignment_0());
		}
		public static IGrammarAwareElementType createModel_IncludesIncludesParserRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Model_IncludesIncludesParserRuleCall_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getIncludesIncludesParserRuleCall_0_0());
		}
		public static IGrammarAwareElementType createModel_Alternatives_1ElementType() {
			return new IGrammarAwareElementType("Model_Alternatives_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getAlternatives_1());
		}
		public static IGrammarAwareElementType createModel_PlanesAssignment_1_0ElementType() {
			return new IGrammarAwareElementType("Model_PlanesAssignment_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getPlanesAssignment_1_0());
		}
		public static IGrammarAwareElementType createModel_PlanesPlaneParserRuleCall_1_0_0ElementType() {
			return new IGrammarAwareElementType("Model_PlanesPlaneParserRuleCall_1_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getPlanesPlaneParserRuleCall_1_0_0());
		}
		public static IGrammarAwareElementType createModel_AirportsAssignment_1_1ElementType() {
			return new IGrammarAwareElementType("Model_AirportsAssignment_1_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getAirportsAssignment_1_1());
		}
		public static IGrammarAwareElementType createModel_AirportsAirportParserRuleCall_1_1_0ElementType() {
			return new IGrammarAwareElementType("Model_AirportsAirportParserRuleCall_1_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getAirportsAirportParserRuleCall_1_1_0());
		}
		public static IGrammarAwareElementType createModel_AirlinesAssignment_2ElementType() {
			return new IGrammarAwareElementType("Model_AirlinesAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getAirlinesAssignment_2());
		}
		public static IGrammarAwareElementType createModel_AirlinesAirlineParserRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Model_AirlinesAirlineParserRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getModelAccess().getAirlinesAirlineParserRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType Model_ELEMENT_TYPE = associate(ModelFactory.createModelElementType());

	public static final IGrammarAwareElementType Model_Group_ELEMENT_TYPE = associate(ModelFactory.createModel_GroupElementType());

	public static final IGrammarAwareElementType Model_IncludesAssignment_0_ELEMENT_TYPE = associate(ModelFactory.createModel_IncludesAssignment_0ElementType());

	public static final IGrammarAwareElementType Model_IncludesIncludesParserRuleCall_0_0_ELEMENT_TYPE = associate(ModelFactory.createModel_IncludesIncludesParserRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Model_Alternatives_1_ELEMENT_TYPE = associate(ModelFactory.createModel_Alternatives_1ElementType());

	public static final IGrammarAwareElementType Model_PlanesAssignment_1_0_ELEMENT_TYPE = associate(ModelFactory.createModel_PlanesAssignment_1_0ElementType());

	public static final IGrammarAwareElementType Model_PlanesPlaneParserRuleCall_1_0_0_ELEMENT_TYPE = associate(ModelFactory.createModel_PlanesPlaneParserRuleCall_1_0_0ElementType());

	public static final IGrammarAwareElementType Model_AirportsAssignment_1_1_ELEMENT_TYPE = associate(ModelFactory.createModel_AirportsAssignment_1_1ElementType());

	public static final IGrammarAwareElementType Model_AirportsAirportParserRuleCall_1_1_0_ELEMENT_TYPE = associate(ModelFactory.createModel_AirportsAirportParserRuleCall_1_1_0ElementType());

	public static final IGrammarAwareElementType Model_AirlinesAssignment_2_ELEMENT_TYPE = associate(ModelFactory.createModel_AirlinesAssignment_2ElementType());

	public static final IGrammarAwareElementType Model_AirlinesAirlineParserRuleCall_2_0_ELEMENT_TYPE = associate(ModelFactory.createModel_AirlinesAirlineParserRuleCall_2_0ElementType());

	private static class IncludesFactory {
		public static IGrammarAwareElementType createIncludesElementType() {
			return new IGrammarAwareElementType("Includes_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesRule());
		}
		public static IGrammarAwareElementType createIncludes_GroupElementType() {
			return new IGrammarAwareElementType("Includes_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getGroup());
		}
		public static IGrammarAwareElementType createIncludes_IncludeKeyword_0ElementType() {
			return new IGrammarAwareElementType("Includes_IncludeKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getIncludeKeyword_0());
		}
		public static IGrammarAwareElementType createIncludes_LessThanSignKeyword_1ElementType() {
			return new IGrammarAwareElementType("Includes_LessThanSignKeyword_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getLessThanSignKeyword_1());
		}
		public static IGrammarAwareElementType createIncludes_ImportURIAssignment_2ElementType() {
			return new IGrammarAwareElementType("Includes_ImportURIAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getImportURIAssignment_2());
		}
		public static IGrammarAwareElementType createIncludes_ImportURIINCLUDETerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Includes_ImportURIINCLUDETerminalRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getImportURIINCLUDETerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createIncludes_GreaterThanSignSemicolonKeyword_3ElementType() {
			return new IGrammarAwareElementType("Includes_GreaterThanSignSemicolonKeyword_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getIncludesAccess().getGreaterThanSignSemicolonKeyword_3());
		}
	}

	public static final IGrammarAwareElementType Includes_ELEMENT_TYPE = associate(IncludesFactory.createIncludesElementType());

	public static final IGrammarAwareElementType Includes_Group_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_GroupElementType());

	public static final IGrammarAwareElementType Includes_IncludeKeyword_0_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_IncludeKeyword_0ElementType());

	public static final IGrammarAwareElementType Includes_LessThanSignKeyword_1_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_LessThanSignKeyword_1ElementType());

	public static final IGrammarAwareElementType Includes_ImportURIAssignment_2_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_ImportURIAssignment_2ElementType());

	public static final IGrammarAwareElementType Includes_ImportURIINCLUDETerminalRuleCall_2_0_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_ImportURIINCLUDETerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType Includes_GreaterThanSignSemicolonKeyword_3_ELEMENT_TYPE = associate(IncludesFactory.createIncludes_GreaterThanSignSemicolonKeyword_3ElementType());

	private static class PlaneFactory {
		public static IGrammarAwareElementType createPlaneElementType() {
			return new IGrammarAwareElementType("Plane_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneRule());
		}
		public static IGrammarAwareElementType createPlane_GroupElementType() {
			return new IGrammarAwareElementType("Plane_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getGroup());
		}
		public static IGrammarAwareElementType createPlane_AvionKeyword_0ElementType() {
			return new IGrammarAwareElementType("Plane_AvionKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getAvionKeyword_0());
		}
		public static IGrammarAwareElementType createPlane_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Plane_NameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createPlane_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Plane_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createPlane_ColonKeyword_2ElementType() {
			return new IGrammarAwareElementType("Plane_ColonKeyword_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getColonKeyword_2());
		}
		public static IGrammarAwareElementType createPlane_UnorderedGroup_3ElementType() {
			return new IGrammarAwareElementType("Plane_UnorderedGroup_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getUnorderedGroup_3());
		}
		public static IGrammarAwareElementType createPlane_Group_3_0ElementType() {
			return new IGrammarAwareElementType("Plane_Group_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getGroup_3_0());
		}
		public static IGrammarAwareElementType createPlane_PassagersKeyword_3_0_0ElementType() {
			return new IGrammarAwareElementType("Plane_PassagersKeyword_3_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getPassagersKeyword_3_0_0());
		}
		public static IGrammarAwareElementType createPlane_ColonKeyword_3_0_1ElementType() {
			return new IGrammarAwareElementType("Plane_ColonKeyword_3_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getColonKeyword_3_0_1());
		}
		public static IGrammarAwareElementType createPlane_PassengersAssignment_3_0_2ElementType() {
			return new IGrammarAwareElementType("Plane_PassengersAssignment_3_0_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getPassengersAssignment_3_0_2());
		}
		public static IGrammarAwareElementType createPlane_PassengersINTTerminalRuleCall_3_0_2_0ElementType() {
			return new IGrammarAwareElementType("Plane_PassengersINTTerminalRuleCall_3_0_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getPassengersINTTerminalRuleCall_3_0_2_0());
		}
		public static IGrammarAwareElementType createPlane_SemicolonKeyword_3_0_3ElementType() {
			return new IGrammarAwareElementType("Plane_SemicolonKeyword_3_0_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getSemicolonKeyword_3_0_3());
		}
		public static IGrammarAwareElementType createPlane_Group_3_1ElementType() {
			return new IGrammarAwareElementType("Plane_Group_3_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getGroup_3_1());
		}
		public static IGrammarAwareElementType createPlane_MotorisationKeyword_3_1_0ElementType() {
			return new IGrammarAwareElementType("Plane_MotorisationKeyword_3_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getMotorisationKeyword_3_1_0());
		}
		public static IGrammarAwareElementType createPlane_ColonKeyword_3_1_1ElementType() {
			return new IGrammarAwareElementType("Plane_ColonKeyword_3_1_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getColonKeyword_3_1_1());
		}
		public static IGrammarAwareElementType createPlane_MotorisationAssignment_3_1_2ElementType() {
			return new IGrammarAwareElementType("Plane_MotorisationAssignment_3_1_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getMotorisationAssignment_3_1_2());
		}
		public static IGrammarAwareElementType createPlane_MotorisationEnginesEnumRuleCall_3_1_2_0ElementType() {
			return new IGrammarAwareElementType("Plane_MotorisationEnginesEnumRuleCall_3_1_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getMotorisationEnginesEnumRuleCall_3_1_2_0());
		}
		public static IGrammarAwareElementType createPlane_SemicolonKeyword_3_1_3ElementType() {
			return new IGrammarAwareElementType("Plane_SemicolonKeyword_3_1_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getSemicolonKeyword_3_1_3());
		}
		public static IGrammarAwareElementType createPlane_EndKeyword_4ElementType() {
			return new IGrammarAwareElementType("Plane_EndKeyword_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPlaneAccess().getEndKeyword_4());
		}
	}

	public static final IGrammarAwareElementType Plane_ELEMENT_TYPE = associate(PlaneFactory.createPlaneElementType());

	public static final IGrammarAwareElementType Plane_Group_ELEMENT_TYPE = associate(PlaneFactory.createPlane_GroupElementType());

	public static final IGrammarAwareElementType Plane_AvionKeyword_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_AvionKeyword_0ElementType());

	public static final IGrammarAwareElementType Plane_NameAssignment_1_ELEMENT_TYPE = associate(PlaneFactory.createPlane_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Plane_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_NameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Plane_ColonKeyword_2_ELEMENT_TYPE = associate(PlaneFactory.createPlane_ColonKeyword_2ElementType());

	public static final IGrammarAwareElementType Plane_UnorderedGroup_3_ELEMENT_TYPE = associate(PlaneFactory.createPlane_UnorderedGroup_3ElementType());

	public static final IGrammarAwareElementType Plane_Group_3_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_Group_3_0ElementType());

	public static final IGrammarAwareElementType Plane_PassagersKeyword_3_0_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_PassagersKeyword_3_0_0ElementType());

	public static final IGrammarAwareElementType Plane_ColonKeyword_3_0_1_ELEMENT_TYPE = associate(PlaneFactory.createPlane_ColonKeyword_3_0_1ElementType());

	public static final IGrammarAwareElementType Plane_PassengersAssignment_3_0_2_ELEMENT_TYPE = associate(PlaneFactory.createPlane_PassengersAssignment_3_0_2ElementType());

	public static final IGrammarAwareElementType Plane_PassengersINTTerminalRuleCall_3_0_2_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_PassengersINTTerminalRuleCall_3_0_2_0ElementType());

	public static final IGrammarAwareElementType Plane_SemicolonKeyword_3_0_3_ELEMENT_TYPE = associate(PlaneFactory.createPlane_SemicolonKeyword_3_0_3ElementType());

	public static final IGrammarAwareElementType Plane_Group_3_1_ELEMENT_TYPE = associate(PlaneFactory.createPlane_Group_3_1ElementType());

	public static final IGrammarAwareElementType Plane_MotorisationKeyword_3_1_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_MotorisationKeyword_3_1_0ElementType());

	public static final IGrammarAwareElementType Plane_ColonKeyword_3_1_1_ELEMENT_TYPE = associate(PlaneFactory.createPlane_ColonKeyword_3_1_1ElementType());

	public static final IGrammarAwareElementType Plane_MotorisationAssignment_3_1_2_ELEMENT_TYPE = associate(PlaneFactory.createPlane_MotorisationAssignment_3_1_2ElementType());

	public static final IGrammarAwareElementType Plane_MotorisationEnginesEnumRuleCall_3_1_2_0_ELEMENT_TYPE = associate(PlaneFactory.createPlane_MotorisationEnginesEnumRuleCall_3_1_2_0ElementType());

	public static final IGrammarAwareElementType Plane_SemicolonKeyword_3_1_3_ELEMENT_TYPE = associate(PlaneFactory.createPlane_SemicolonKeyword_3_1_3ElementType());

	public static final IGrammarAwareElementType Plane_EndKeyword_4_ELEMENT_TYPE = associate(PlaneFactory.createPlane_EndKeyword_4ElementType());

	private static class AirportFactory {
		public static IGrammarAwareElementType createAirportElementType() {
			return new IGrammarAwareElementType("Airport_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportRule());
		}
		public static IGrammarAwareElementType createAirport_GroupElementType() {
			return new IGrammarAwareElementType("Airport_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getGroup());
		}
		public static IGrammarAwareElementType createAirport_AeroportKeyword_0ElementType() {
			return new IGrammarAwareElementType("Airport_AeroportKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getAeroportKeyword_0());
		}
		public static IGrammarAwareElementType createAirport_TitleAssignment_1ElementType() {
			return new IGrammarAwareElementType("Airport_TitleAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getTitleAssignment_1());
		}
		public static IGrammarAwareElementType createAirport_TitleSTRINGTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Airport_TitleSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getTitleSTRINGTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createAirport_ColonKeyword_2ElementType() {
			return new IGrammarAwareElementType("Airport_ColonKeyword_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getColonKeyword_2());
		}
		public static IGrammarAwareElementType createAirport_UnorderedGroup_3ElementType() {
			return new IGrammarAwareElementType("Airport_UnorderedGroup_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getUnorderedGroup_3());
		}
		public static IGrammarAwareElementType createAirport_Group_3_0ElementType() {
			return new IGrammarAwareElementType("Airport_Group_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getGroup_3_0());
		}
		public static IGrammarAwareElementType createAirport_OACIKeyword_3_0_0ElementType() {
			return new IGrammarAwareElementType("Airport_OACIKeyword_3_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getOACIKeyword_3_0_0());
		}
		public static IGrammarAwareElementType createAirport_ColonKeyword_3_0_1ElementType() {
			return new IGrammarAwareElementType("Airport_ColonKeyword_3_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getColonKeyword_3_0_1());
		}
		public static IGrammarAwareElementType createAirport_NameAssignment_3_0_2ElementType() {
			return new IGrammarAwareElementType("Airport_NameAssignment_3_0_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getNameAssignment_3_0_2());
		}
		public static IGrammarAwareElementType createAirport_NameCodeOACIParserRuleCall_3_0_2_0ElementType() {
			return new IGrammarAwareElementType("Airport_NameCodeOACIParserRuleCall_3_0_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getNameCodeOACIParserRuleCall_3_0_2_0());
		}
		public static IGrammarAwareElementType createAirport_SemicolonKeyword_3_0_3ElementType() {
			return new IGrammarAwareElementType("Airport_SemicolonKeyword_3_0_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getSemicolonKeyword_3_0_3());
		}
		public static IGrammarAwareElementType createAirport_Group_3_1ElementType() {
			return new IGrammarAwareElementType("Airport_Group_3_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getGroup_3_1());
		}
		public static IGrammarAwareElementType createAirport_PaysKeyword_3_1_0ElementType() {
			return new IGrammarAwareElementType("Airport_PaysKeyword_3_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getPaysKeyword_3_1_0());
		}
		public static IGrammarAwareElementType createAirport_ColonKeyword_3_1_1ElementType() {
			return new IGrammarAwareElementType("Airport_ColonKeyword_3_1_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getColonKeyword_3_1_1());
		}
		public static IGrammarAwareElementType createAirport_CountryAssignment_3_1_2ElementType() {
			return new IGrammarAwareElementType("Airport_CountryAssignment_3_1_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getCountryAssignment_3_1_2());
		}
		public static IGrammarAwareElementType createAirport_CountrySTRINGTerminalRuleCall_3_1_2_0ElementType() {
			return new IGrammarAwareElementType("Airport_CountrySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getCountrySTRINGTerminalRuleCall_3_1_2_0());
		}
		public static IGrammarAwareElementType createAirport_SemicolonKeyword_3_1_3ElementType() {
			return new IGrammarAwareElementType("Airport_SemicolonKeyword_3_1_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getSemicolonKeyword_3_1_3());
		}
		public static IGrammarAwareElementType createAirport_Group_3_2ElementType() {
			return new IGrammarAwareElementType("Airport_Group_3_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getGroup_3_2());
		}
		public static IGrammarAwareElementType createAirport_PistesKeyword_3_2_0ElementType() {
			return new IGrammarAwareElementType("Airport_PistesKeyword_3_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getPistesKeyword_3_2_0());
		}
		public static IGrammarAwareElementType createAirport_ColonKeyword_3_2_1ElementType() {
			return new IGrammarAwareElementType("Airport_ColonKeyword_3_2_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getColonKeyword_3_2_1());
		}
		public static IGrammarAwareElementType createAirport_RunwaysAssignment_3_2_2ElementType() {
			return new IGrammarAwareElementType("Airport_RunwaysAssignment_3_2_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getRunwaysAssignment_3_2_2());
		}
		public static IGrammarAwareElementType createAirport_RunwaysINTTerminalRuleCall_3_2_2_0ElementType() {
			return new IGrammarAwareElementType("Airport_RunwaysINTTerminalRuleCall_3_2_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getRunwaysINTTerminalRuleCall_3_2_2_0());
		}
		public static IGrammarAwareElementType createAirport_SemicolonKeyword_3_2_3ElementType() {
			return new IGrammarAwareElementType("Airport_SemicolonKeyword_3_2_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getSemicolonKeyword_3_2_3());
		}
		public static IGrammarAwareElementType createAirport_EndKeyword_4ElementType() {
			return new IGrammarAwareElementType("Airport_EndKeyword_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirportAccess().getEndKeyword_4());
		}
	}

	public static final IGrammarAwareElementType Airport_ELEMENT_TYPE = associate(AirportFactory.createAirportElementType());

	public static final IGrammarAwareElementType Airport_Group_ELEMENT_TYPE = associate(AirportFactory.createAirport_GroupElementType());

	public static final IGrammarAwareElementType Airport_AeroportKeyword_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_AeroportKeyword_0ElementType());

	public static final IGrammarAwareElementType Airport_TitleAssignment_1_ELEMENT_TYPE = associate(AirportFactory.createAirport_TitleAssignment_1ElementType());

	public static final IGrammarAwareElementType Airport_TitleSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_TitleSTRINGTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Airport_ColonKeyword_2_ELEMENT_TYPE = associate(AirportFactory.createAirport_ColonKeyword_2ElementType());

	public static final IGrammarAwareElementType Airport_UnorderedGroup_3_ELEMENT_TYPE = associate(AirportFactory.createAirport_UnorderedGroup_3ElementType());

	public static final IGrammarAwareElementType Airport_Group_3_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_Group_3_0ElementType());

	public static final IGrammarAwareElementType Airport_OACIKeyword_3_0_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_OACIKeyword_3_0_0ElementType());

	public static final IGrammarAwareElementType Airport_ColonKeyword_3_0_1_ELEMENT_TYPE = associate(AirportFactory.createAirport_ColonKeyword_3_0_1ElementType());

	public static final IGrammarAwareElementType Airport_NameAssignment_3_0_2_ELEMENT_TYPE = associate(AirportFactory.createAirport_NameAssignment_3_0_2ElementType());

	public static final IGrammarAwareElementType Airport_NameCodeOACIParserRuleCall_3_0_2_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_NameCodeOACIParserRuleCall_3_0_2_0ElementType());

	public static final IGrammarAwareElementType Airport_SemicolonKeyword_3_0_3_ELEMENT_TYPE = associate(AirportFactory.createAirport_SemicolonKeyword_3_0_3ElementType());

	public static final IGrammarAwareElementType Airport_Group_3_1_ELEMENT_TYPE = associate(AirportFactory.createAirport_Group_3_1ElementType());

	public static final IGrammarAwareElementType Airport_PaysKeyword_3_1_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_PaysKeyword_3_1_0ElementType());

	public static final IGrammarAwareElementType Airport_ColonKeyword_3_1_1_ELEMENT_TYPE = associate(AirportFactory.createAirport_ColonKeyword_3_1_1ElementType());

	public static final IGrammarAwareElementType Airport_CountryAssignment_3_1_2_ELEMENT_TYPE = associate(AirportFactory.createAirport_CountryAssignment_3_1_2ElementType());

	public static final IGrammarAwareElementType Airport_CountrySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_CountrySTRINGTerminalRuleCall_3_1_2_0ElementType());

	public static final IGrammarAwareElementType Airport_SemicolonKeyword_3_1_3_ELEMENT_TYPE = associate(AirportFactory.createAirport_SemicolonKeyword_3_1_3ElementType());

	public static final IGrammarAwareElementType Airport_Group_3_2_ELEMENT_TYPE = associate(AirportFactory.createAirport_Group_3_2ElementType());

	public static final IGrammarAwareElementType Airport_PistesKeyword_3_2_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_PistesKeyword_3_2_0ElementType());

	public static final IGrammarAwareElementType Airport_ColonKeyword_3_2_1_ELEMENT_TYPE = associate(AirportFactory.createAirport_ColonKeyword_3_2_1ElementType());

	public static final IGrammarAwareElementType Airport_RunwaysAssignment_3_2_2_ELEMENT_TYPE = associate(AirportFactory.createAirport_RunwaysAssignment_3_2_2ElementType());

	public static final IGrammarAwareElementType Airport_RunwaysINTTerminalRuleCall_3_2_2_0_ELEMENT_TYPE = associate(AirportFactory.createAirport_RunwaysINTTerminalRuleCall_3_2_2_0ElementType());

	public static final IGrammarAwareElementType Airport_SemicolonKeyword_3_2_3_ELEMENT_TYPE = associate(AirportFactory.createAirport_SemicolonKeyword_3_2_3ElementType());

	public static final IGrammarAwareElementType Airport_EndKeyword_4_ELEMENT_TYPE = associate(AirportFactory.createAirport_EndKeyword_4ElementType());

	private static class AirlineFactory {
		public static IGrammarAwareElementType createAirlineElementType() {
			return new IGrammarAwareElementType("Airline_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineRule());
		}
		public static IGrammarAwareElementType createAirline_GroupElementType() {
			return new IGrammarAwareElementType("Airline_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup());
		}
		public static IGrammarAwareElementType createAirline_LigneKeyword_0ElementType() {
			return new IGrammarAwareElementType("Airline_LigneKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getLigneKeyword_0());
		}
		public static IGrammarAwareElementType createAirline_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Airline_NameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createAirline_NameSTRINGTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Airline_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getNameSTRINGTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_2ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_2());
		}
		public static IGrammarAwareElementType createAirline_UnorderedGroup_3ElementType() {
			return new IGrammarAwareElementType("Airline_UnorderedGroup_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getUnorderedGroup_3());
		}
		public static IGrammarAwareElementType createAirline_Group_3_0ElementType() {
			return new IGrammarAwareElementType("Airline_Group_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup_3_0());
		}
		public static IGrammarAwareElementType createAirline_AvionKeyword_3_0_0ElementType() {
			return new IGrammarAwareElementType("Airline_AvionKeyword_3_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getAvionKeyword_3_0_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_3_0_1ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_3_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_3_0_1());
		}
		public static IGrammarAwareElementType createAirline_PlaneAssignment_3_0_2ElementType() {
			return new IGrammarAwareElementType("Airline_PlaneAssignment_3_0_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getPlaneAssignment_3_0_2());
		}
		public static IGrammarAwareElementType createAirline_PlanePlaneCrossReference_3_0_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_PlanePlaneCrossReference_3_0_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getPlanePlaneCrossReference_3_0_2_0());
		}
		public static IGrammarAwareElementType createAirline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1ElementType() {
			return new IGrammarAwareElementType("Airline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getPlanePlaneIDTerminalRuleCall_3_0_2_0_1());
		}
		public static IGrammarAwareElementType createAirline_SemicolonKeyword_3_0_3ElementType() {
			return new IGrammarAwareElementType("Airline_SemicolonKeyword_3_0_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getSemicolonKeyword_3_0_3());
		}
		public static IGrammarAwareElementType createAirline_Group_3_1ElementType() {
			return new IGrammarAwareElementType("Airline_Group_3_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup_3_1());
		}
		public static IGrammarAwareElementType createAirline_CompagnieKeyword_3_1_0ElementType() {
			return new IGrammarAwareElementType("Airline_CompagnieKeyword_3_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getCompagnieKeyword_3_1_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_3_1_1ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_3_1_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_3_1_1());
		}
		public static IGrammarAwareElementType createAirline_CompanyAssignment_3_1_2ElementType() {
			return new IGrammarAwareElementType("Airline_CompanyAssignment_3_1_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getCompanyAssignment_3_1_2());
		}
		public static IGrammarAwareElementType createAirline_CompanySTRINGTerminalRuleCall_3_1_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_CompanySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getCompanySTRINGTerminalRuleCall_3_1_2_0());
		}
		public static IGrammarAwareElementType createAirline_SemicolonKeyword_3_1_3ElementType() {
			return new IGrammarAwareElementType("Airline_SemicolonKeyword_3_1_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getSemicolonKeyword_3_1_3());
		}
		public static IGrammarAwareElementType createAirline_Group_3_2ElementType() {
			return new IGrammarAwareElementType("Airline_Group_3_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup_3_2());
		}
		public static IGrammarAwareElementType createAirline_DepartKeyword_3_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_DepartKeyword_3_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDepartKeyword_3_2_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_3_2_1ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_3_2_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_3_2_1());
		}
		public static IGrammarAwareElementType createAirline_DepartureAssignment_3_2_2ElementType() {
			return new IGrammarAwareElementType("Airline_DepartureAssignment_3_2_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDepartureAssignment_3_2_2());
		}
		public static IGrammarAwareElementType createAirline_DepartureCodeOACICrossReference_3_2_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_DepartureCodeOACICrossReference_3_2_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDepartureCodeOACICrossReference_3_2_2_0());
		}
		public static IGrammarAwareElementType createAirline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1ElementType() {
			return new IGrammarAwareElementType("Airline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1());
		}
		public static IGrammarAwareElementType createAirline_SemicolonKeyword_3_2_3ElementType() {
			return new IGrammarAwareElementType("Airline_SemicolonKeyword_3_2_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getSemicolonKeyword_3_2_3());
		}
		public static IGrammarAwareElementType createAirline_Group_3_3ElementType() {
			return new IGrammarAwareElementType("Airline_Group_3_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup_3_3());
		}
		public static IGrammarAwareElementType createAirline_ArriveeKeyword_3_3_0ElementType() {
			return new IGrammarAwareElementType("Airline_ArriveeKeyword_3_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getArriveeKeyword_3_3_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_3_3_1ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_3_3_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_3_3_1());
		}
		public static IGrammarAwareElementType createAirline_ArrivalAssignment_3_3_2ElementType() {
			return new IGrammarAwareElementType("Airline_ArrivalAssignment_3_3_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getArrivalAssignment_3_3_2());
		}
		public static IGrammarAwareElementType createAirline_ArrivalCodeOACICrossReference_3_3_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_ArrivalCodeOACICrossReference_3_3_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getArrivalCodeOACICrossReference_3_3_2_0());
		}
		public static IGrammarAwareElementType createAirline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1ElementType() {
			return new IGrammarAwareElementType("Airline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1());
		}
		public static IGrammarAwareElementType createAirline_SemicolonKeyword_3_3_3ElementType() {
			return new IGrammarAwareElementType("Airline_SemicolonKeyword_3_3_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getSemicolonKeyword_3_3_3());
		}
		public static IGrammarAwareElementType createAirline_Group_3_4ElementType() {
			return new IGrammarAwareElementType("Airline_Group_3_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getGroup_3_4());
		}
		public static IGrammarAwareElementType createAirline_DureeKeyword_3_4_0ElementType() {
			return new IGrammarAwareElementType("Airline_DureeKeyword_3_4_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDureeKeyword_3_4_0());
		}
		public static IGrammarAwareElementType createAirline_ColonKeyword_3_4_1ElementType() {
			return new IGrammarAwareElementType("Airline_ColonKeyword_3_4_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getColonKeyword_3_4_1());
		}
		public static IGrammarAwareElementType createAirline_DurationAssignment_3_4_2ElementType() {
			return new IGrammarAwareElementType("Airline_DurationAssignment_3_4_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDurationAssignment_3_4_2());
		}
		public static IGrammarAwareElementType createAirline_DurationDURATIONTerminalRuleCall_3_4_2_0ElementType() {
			return new IGrammarAwareElementType("Airline_DurationDURATIONTerminalRuleCall_3_4_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getDurationDURATIONTerminalRuleCall_3_4_2_0());
		}
		public static IGrammarAwareElementType createAirline_SemicolonKeyword_3_4_3ElementType() {
			return new IGrammarAwareElementType("Airline_SemicolonKeyword_3_4_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getSemicolonKeyword_3_4_3());
		}
		public static IGrammarAwareElementType createAirline_RegularAssignment_3_5ElementType() {
			return new IGrammarAwareElementType("Airline_RegularAssignment_3_5_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getRegularAssignment_3_5());
		}
		public static IGrammarAwareElementType createAirline_RegularREGULIEREKeyword_3_5_0ElementType() {
			return new IGrammarAwareElementType("Airline_RegularREGULIEREKeyword_3_5_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getRegularREGULIEREKeyword_3_5_0());
		}
		public static IGrammarAwareElementType createAirline_EndKeyword_4ElementType() {
			return new IGrammarAwareElementType("Airline_EndKeyword_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAirlineAccess().getEndKeyword_4());
		}
	}

	public static final IGrammarAwareElementType Airline_ELEMENT_TYPE = associate(AirlineFactory.createAirlineElementType());

	public static final IGrammarAwareElementType Airline_Group_ELEMENT_TYPE = associate(AirlineFactory.createAirline_GroupElementType());

	public static final IGrammarAwareElementType Airline_LigneKeyword_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_LigneKeyword_0ElementType());

	public static final IGrammarAwareElementType Airline_NameAssignment_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Airline_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_NameSTRINGTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_2ElementType());

	public static final IGrammarAwareElementType Airline_UnorderedGroup_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_UnorderedGroup_3ElementType());

	public static final IGrammarAwareElementType Airline_Group_3_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_Group_3_0ElementType());

	public static final IGrammarAwareElementType Airline_AvionKeyword_3_0_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_AvionKeyword_3_0_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_3_0_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_3_0_1ElementType());

	public static final IGrammarAwareElementType Airline_PlaneAssignment_3_0_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_PlaneAssignment_3_0_2ElementType());

	public static final IGrammarAwareElementType Airline_PlanePlaneCrossReference_3_0_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_PlanePlaneCrossReference_3_0_2_0ElementType());

	public static final IGrammarAwareElementType Airline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1ElementType());

	public static final IGrammarAwareElementType Airline_SemicolonKeyword_3_0_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_SemicolonKeyword_3_0_3ElementType());

	public static final IGrammarAwareElementType Airline_Group_3_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_Group_3_1ElementType());

	public static final IGrammarAwareElementType Airline_CompagnieKeyword_3_1_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_CompagnieKeyword_3_1_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_3_1_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_3_1_1ElementType());

	public static final IGrammarAwareElementType Airline_CompanyAssignment_3_1_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_CompanyAssignment_3_1_2ElementType());

	public static final IGrammarAwareElementType Airline_CompanySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_CompanySTRINGTerminalRuleCall_3_1_2_0ElementType());

	public static final IGrammarAwareElementType Airline_SemicolonKeyword_3_1_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_SemicolonKeyword_3_1_3ElementType());

	public static final IGrammarAwareElementType Airline_Group_3_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_Group_3_2ElementType());

	public static final IGrammarAwareElementType Airline_DepartKeyword_3_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DepartKeyword_3_2_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_3_2_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_3_2_1ElementType());

	public static final IGrammarAwareElementType Airline_DepartureAssignment_3_2_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DepartureAssignment_3_2_2ElementType());

	public static final IGrammarAwareElementType Airline_DepartureCodeOACICrossReference_3_2_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DepartureCodeOACICrossReference_3_2_2_0ElementType());

	public static final IGrammarAwareElementType Airline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1ElementType());

	public static final IGrammarAwareElementType Airline_SemicolonKeyword_3_2_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_SemicolonKeyword_3_2_3ElementType());

	public static final IGrammarAwareElementType Airline_Group_3_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_Group_3_3ElementType());

	public static final IGrammarAwareElementType Airline_ArriveeKeyword_3_3_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ArriveeKeyword_3_3_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_3_3_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_3_3_1ElementType());

	public static final IGrammarAwareElementType Airline_ArrivalAssignment_3_3_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ArrivalAssignment_3_3_2ElementType());

	public static final IGrammarAwareElementType Airline_ArrivalCodeOACICrossReference_3_3_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ArrivalCodeOACICrossReference_3_3_2_0ElementType());

	public static final IGrammarAwareElementType Airline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1ElementType());

	public static final IGrammarAwareElementType Airline_SemicolonKeyword_3_3_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_SemicolonKeyword_3_3_3ElementType());

	public static final IGrammarAwareElementType Airline_Group_3_4_ELEMENT_TYPE = associate(AirlineFactory.createAirline_Group_3_4ElementType());

	public static final IGrammarAwareElementType Airline_DureeKeyword_3_4_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DureeKeyword_3_4_0ElementType());

	public static final IGrammarAwareElementType Airline_ColonKeyword_3_4_1_ELEMENT_TYPE = associate(AirlineFactory.createAirline_ColonKeyword_3_4_1ElementType());

	public static final IGrammarAwareElementType Airline_DurationAssignment_3_4_2_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DurationAssignment_3_4_2ElementType());

	public static final IGrammarAwareElementType Airline_DurationDURATIONTerminalRuleCall_3_4_2_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_DurationDURATIONTerminalRuleCall_3_4_2_0ElementType());

	public static final IGrammarAwareElementType Airline_SemicolonKeyword_3_4_3_ELEMENT_TYPE = associate(AirlineFactory.createAirline_SemicolonKeyword_3_4_3ElementType());

	public static final IGrammarAwareElementType Airline_RegularAssignment_3_5_ELEMENT_TYPE = associate(AirlineFactory.createAirline_RegularAssignment_3_5ElementType());

	public static final IGrammarAwareElementType Airline_RegularREGULIEREKeyword_3_5_0_ELEMENT_TYPE = associate(AirlineFactory.createAirline_RegularREGULIEREKeyword_3_5_0ElementType());

	public static final IGrammarAwareElementType Airline_EndKeyword_4_ELEMENT_TYPE = associate(AirlineFactory.createAirline_EndKeyword_4ElementType());

	private static class EnginesFactory {
		public static IGrammarAwareElementType createEnginesElementType() {
			return new IGrammarAwareElementType("Engines_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesRule());
		}
		public static IGrammarAwareElementType createEngines_AlternativesElementType() {
			return new IGrammarAwareElementType("Engines_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createEngines_PROPELLEREnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Engines_PROPELLEREnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesAccess().getPROPELLEREnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createEngines_PROPELLERHELICESKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Engines_PROPELLERHELICESKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesAccess().getPROPELLERHELICESKeyword_0_0());
		}
		public static IGrammarAwareElementType createEngines_ENGINEEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Engines_ENGINEEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesAccess().getENGINEEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createEngines_ENGINEPROPULSEURSKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Engines_ENGINEPROPULSEURSKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEnginesAccess().getENGINEPROPULSEURSKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType Engines_ELEMENT_TYPE = associate(EnginesFactory.createEnginesElementType());

	public static final IGrammarAwareElementType Engines_Alternatives_ELEMENT_TYPE = associate(EnginesFactory.createEngines_AlternativesElementType());

	public static final IGrammarAwareElementType Engines_PROPELLEREnumLiteralDeclaration_0_ELEMENT_TYPE = associate(EnginesFactory.createEngines_PROPELLEREnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Engines_PROPELLERHELICESKeyword_0_0_ELEMENT_TYPE = associate(EnginesFactory.createEngines_PROPELLERHELICESKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Engines_ENGINEEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(EnginesFactory.createEngines_ENGINEEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Engines_ENGINEPROPULSEURSKeyword_1_0_ELEMENT_TYPE = associate(EnginesFactory.createEngines_ENGINEPROPULSEURSKeyword_1_0ElementType());

	private static class CodeOACIFactory {
		public static IGrammarAwareElementType createCodeOACIElementType() {
			return new IGrammarAwareElementType("CodeOACI_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getCodeOACIRule());
		}
		public static IGrammarAwareElementType createCodeOACI_NameAssignmentElementType() {
			return new IGrammarAwareElementType("CodeOACI_NameAssignment_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getCodeOACIAccess().getNameAssignment());
		}
		public static IGrammarAwareElementType createCodeOACI_NameOACITerminalRuleCall_0ElementType() {
			return new IGrammarAwareElementType("CodeOACI_NameOACITerminalRuleCall_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getCodeOACIAccess().getNameOACITerminalRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType CodeOACI_ELEMENT_TYPE = associate(CodeOACIFactory.createCodeOACIElementType());

	public static final IGrammarAwareElementType CodeOACI_NameAssignment_ELEMENT_TYPE = associate(CodeOACIFactory.createCodeOACI_NameAssignmentElementType());

	public static final IGrammarAwareElementType CodeOACI_NameOACITerminalRuleCall_0_ELEMENT_TYPE = associate(CodeOACIFactory.createCodeOACI_NameOACITerminalRuleCall_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getModelElementType() {
		return Model_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_GroupElementType() {
		return Model_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_IncludesAssignment_0ElementType() {
		return Model_IncludesAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_IncludesIncludesParserRuleCall_0_0ElementType() {
		return Model_IncludesIncludesParserRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_Alternatives_1ElementType() {
		return Model_Alternatives_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_PlanesAssignment_1_0ElementType() {
		return Model_PlanesAssignment_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_PlanesPlaneParserRuleCall_1_0_0ElementType() {
		return Model_PlanesPlaneParserRuleCall_1_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_AirportsAssignment_1_1ElementType() {
		return Model_AirportsAssignment_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_AirportsAirportParserRuleCall_1_1_0ElementType() {
		return Model_AirportsAirportParserRuleCall_1_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_AirlinesAssignment_2ElementType() {
		return Model_AirlinesAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getModel_AirlinesAirlineParserRuleCall_2_0ElementType() {
		return Model_AirlinesAirlineParserRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludesElementType() {
		return Includes_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_GroupElementType() {
		return Includes_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_IncludeKeyword_0ElementType() {
		return Includes_IncludeKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_LessThanSignKeyword_1ElementType() {
		return Includes_LessThanSignKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_ImportURIAssignment_2ElementType() {
		return Includes_ImportURIAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_ImportURIINCLUDETerminalRuleCall_2_0ElementType() {
		return Includes_ImportURIINCLUDETerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIncludes_GreaterThanSignSemicolonKeyword_3ElementType() {
		return Includes_GreaterThanSignSemicolonKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlaneElementType() {
		return Plane_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_GroupElementType() {
		return Plane_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_AvionKeyword_0ElementType() {
		return Plane_AvionKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_NameAssignment_1ElementType() {
		return Plane_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_NameIDTerminalRuleCall_1_0ElementType() {
		return Plane_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_ColonKeyword_2ElementType() {
		return Plane_ColonKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_UnorderedGroup_3ElementType() {
		return Plane_UnorderedGroup_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_Group_3_0ElementType() {
		return Plane_Group_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_PassagersKeyword_3_0_0ElementType() {
		return Plane_PassagersKeyword_3_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_ColonKeyword_3_0_1ElementType() {
		return Plane_ColonKeyword_3_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_PassengersAssignment_3_0_2ElementType() {
		return Plane_PassengersAssignment_3_0_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_PassengersINTTerminalRuleCall_3_0_2_0ElementType() {
		return Plane_PassengersINTTerminalRuleCall_3_0_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_SemicolonKeyword_3_0_3ElementType() {
		return Plane_SemicolonKeyword_3_0_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_Group_3_1ElementType() {
		return Plane_Group_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_MotorisationKeyword_3_1_0ElementType() {
		return Plane_MotorisationKeyword_3_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_ColonKeyword_3_1_1ElementType() {
		return Plane_ColonKeyword_3_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_MotorisationAssignment_3_1_2ElementType() {
		return Plane_MotorisationAssignment_3_1_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_MotorisationEnginesEnumRuleCall_3_1_2_0ElementType() {
		return Plane_MotorisationEnginesEnumRuleCall_3_1_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_SemicolonKeyword_3_1_3ElementType() {
		return Plane_SemicolonKeyword_3_1_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPlane_EndKeyword_4ElementType() {
		return Plane_EndKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirportElementType() {
		return Airport_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_GroupElementType() {
		return Airport_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_AeroportKeyword_0ElementType() {
		return Airport_AeroportKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_TitleAssignment_1ElementType() {
		return Airport_TitleAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_TitleSTRINGTerminalRuleCall_1_0ElementType() {
		return Airport_TitleSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_ColonKeyword_2ElementType() {
		return Airport_ColonKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_UnorderedGroup_3ElementType() {
		return Airport_UnorderedGroup_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_Group_3_0ElementType() {
		return Airport_Group_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_OACIKeyword_3_0_0ElementType() {
		return Airport_OACIKeyword_3_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_ColonKeyword_3_0_1ElementType() {
		return Airport_ColonKeyword_3_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_NameAssignment_3_0_2ElementType() {
		return Airport_NameAssignment_3_0_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_NameCodeOACIParserRuleCall_3_0_2_0ElementType() {
		return Airport_NameCodeOACIParserRuleCall_3_0_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_SemicolonKeyword_3_0_3ElementType() {
		return Airport_SemicolonKeyword_3_0_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_Group_3_1ElementType() {
		return Airport_Group_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_PaysKeyword_3_1_0ElementType() {
		return Airport_PaysKeyword_3_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_ColonKeyword_3_1_1ElementType() {
		return Airport_ColonKeyword_3_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_CountryAssignment_3_1_2ElementType() {
		return Airport_CountryAssignment_3_1_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_CountrySTRINGTerminalRuleCall_3_1_2_0ElementType() {
		return Airport_CountrySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_SemicolonKeyword_3_1_3ElementType() {
		return Airport_SemicolonKeyword_3_1_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_Group_3_2ElementType() {
		return Airport_Group_3_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_PistesKeyword_3_2_0ElementType() {
		return Airport_PistesKeyword_3_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_ColonKeyword_3_2_1ElementType() {
		return Airport_ColonKeyword_3_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_RunwaysAssignment_3_2_2ElementType() {
		return Airport_RunwaysAssignment_3_2_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_RunwaysINTTerminalRuleCall_3_2_2_0ElementType() {
		return Airport_RunwaysINTTerminalRuleCall_3_2_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_SemicolonKeyword_3_2_3ElementType() {
		return Airport_SemicolonKeyword_3_2_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirport_EndKeyword_4ElementType() {
		return Airport_EndKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirlineElementType() {
		return Airline_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_GroupElementType() {
		return Airline_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_LigneKeyword_0ElementType() {
		return Airline_LigneKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_NameAssignment_1ElementType() {
		return Airline_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_NameSTRINGTerminalRuleCall_1_0ElementType() {
		return Airline_NameSTRINGTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_2ElementType() {
		return Airline_ColonKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_UnorderedGroup_3ElementType() {
		return Airline_UnorderedGroup_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_Group_3_0ElementType() {
		return Airline_Group_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_AvionKeyword_3_0_0ElementType() {
		return Airline_AvionKeyword_3_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_3_0_1ElementType() {
		return Airline_ColonKeyword_3_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_PlaneAssignment_3_0_2ElementType() {
		return Airline_PlaneAssignment_3_0_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_PlanePlaneCrossReference_3_0_2_0ElementType() {
		return Airline_PlanePlaneCrossReference_3_0_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1ElementType() {
		return Airline_PlanePlaneIDTerminalRuleCall_3_0_2_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_SemicolonKeyword_3_0_3ElementType() {
		return Airline_SemicolonKeyword_3_0_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_Group_3_1ElementType() {
		return Airline_Group_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_CompagnieKeyword_3_1_0ElementType() {
		return Airline_CompagnieKeyword_3_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_3_1_1ElementType() {
		return Airline_ColonKeyword_3_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_CompanyAssignment_3_1_2ElementType() {
		return Airline_CompanyAssignment_3_1_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_CompanySTRINGTerminalRuleCall_3_1_2_0ElementType() {
		return Airline_CompanySTRINGTerminalRuleCall_3_1_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_SemicolonKeyword_3_1_3ElementType() {
		return Airline_SemicolonKeyword_3_1_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_Group_3_2ElementType() {
		return Airline_Group_3_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DepartKeyword_3_2_0ElementType() {
		return Airline_DepartKeyword_3_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_3_2_1ElementType() {
		return Airline_ColonKeyword_3_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DepartureAssignment_3_2_2ElementType() {
		return Airline_DepartureAssignment_3_2_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DepartureCodeOACICrossReference_3_2_2_0ElementType() {
		return Airline_DepartureCodeOACICrossReference_3_2_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1ElementType() {
		return Airline_DepartureCodeOACIOACITerminalRuleCall_3_2_2_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_SemicolonKeyword_3_2_3ElementType() {
		return Airline_SemicolonKeyword_3_2_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_Group_3_3ElementType() {
		return Airline_Group_3_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ArriveeKeyword_3_3_0ElementType() {
		return Airline_ArriveeKeyword_3_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_3_3_1ElementType() {
		return Airline_ColonKeyword_3_3_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ArrivalAssignment_3_3_2ElementType() {
		return Airline_ArrivalAssignment_3_3_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ArrivalCodeOACICrossReference_3_3_2_0ElementType() {
		return Airline_ArrivalCodeOACICrossReference_3_3_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1ElementType() {
		return Airline_ArrivalCodeOACIOACITerminalRuleCall_3_3_2_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_SemicolonKeyword_3_3_3ElementType() {
		return Airline_SemicolonKeyword_3_3_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_Group_3_4ElementType() {
		return Airline_Group_3_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DureeKeyword_3_4_0ElementType() {
		return Airline_DureeKeyword_3_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_ColonKeyword_3_4_1ElementType() {
		return Airline_ColonKeyword_3_4_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DurationAssignment_3_4_2ElementType() {
		return Airline_DurationAssignment_3_4_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_DurationDURATIONTerminalRuleCall_3_4_2_0ElementType() {
		return Airline_DurationDURATIONTerminalRuleCall_3_4_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_SemicolonKeyword_3_4_3ElementType() {
		return Airline_SemicolonKeyword_3_4_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_RegularAssignment_3_5ElementType() {
		return Airline_RegularAssignment_3_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_RegularREGULIEREKeyword_3_5_0ElementType() {
		return Airline_RegularREGULIEREKeyword_3_5_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAirline_EndKeyword_4ElementType() {
		return Airline_EndKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEnginesElementType() {
		return Engines_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEngines_AlternativesElementType() {
		return Engines_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEngines_PROPELLEREnumLiteralDeclaration_0ElementType() {
		return Engines_PROPELLEREnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEngines_PROPELLERHELICESKeyword_0_0ElementType() {
		return Engines_PROPELLERHELICESKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEngines_ENGINEEnumLiteralDeclaration_1ElementType() {
		return Engines_ENGINEEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEngines_ENGINEPROPULSEURSKeyword_1_0ElementType() {
		return Engines_ENGINEPROPULSEURSKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCodeOACIElementType() {
		return CodeOACI_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCodeOACI_NameAssignmentElementType() {
		return CodeOACI_NameAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCodeOACI_NameOACITerminalRuleCall_0ElementType() {
		return CodeOACI_NameOACITerminalRuleCall_0_ELEMENT_TYPE;
	}

}
