/**
 * generated by Xtext 2.9.0
 */
package org.xtext.aic.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.aic.dsl.ui.AbstractAiC_DSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AiC_DSLUiModule extends AbstractAiC_DSLUiModule {
  public AiC_DSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
